<a href="https://colab.research.google.com/github/likhithaMantaral/Python-in-DA_-and_-ML/blob/master/Day3-session2-exercise%20problrms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10000

In [ ]:
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
d = pd.Series([i for i in range(1000,2001) if i%5==0]) 
print(d)
print(d.tolist())
print(type(d.tolist()))

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64
[1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045, 1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 1120, 1125, 1130, 1135, 1140, 1145, 1150, 1155, 1160, 1165, 1170, 1175, 1180, 1185, 1190, 1195, 1200, 1205, 1210, 1215, 1220, 1225, 1230, 1235, 1240, 1245, 1250, 1255, 1260, 1265, 1270, 1275, 1280, 1285, 1290, 1295, 1300, 1305, 1310, 1315, 1320, 1325, 1330, 1335, 1340, 1345, 1350, 1355, 1360, 1365, 1370, 1375, 1380, 1385, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1425, 1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480, 1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535, 1540, 1545, 1550, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590, 1595, 1600, 1605, 1610, 1615, 1620, 1625, 1630, 1635, 1640, 1645, 1650, 1655, 1660, 1665, 1670, 1675, 1680, 1685, 1690, 1695, 1

Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
l1=([i for i in range(1,101) if i%2==0])
l2=([i for i in range(1,100) if i%2==1])
d1=pd.Series(l1)
d2=pd.Series(l2)
print(f'Addition Of  Two Series:\n{d1+d2}')
print(f'Subtraction Of  Two Series:\n{d1-d2}')
print(f'Multiplication Of  Two Series:\n{d1*d2}')
print(f'Division Of  Two Series:\n{d1/d2}')

Addition Of  Two Series:
0       3
1       7
2      11
3      15
4      19
5      23
6      27
7      31
8      35
9      39
10     43
11     47
12     51
13     55
14     59
15     63
16     67
17     71
18     75
19     79
20     83
21     87
22     91
23     95
24     99
25    103
26    107
27    111
28    115
29    119
30    123
31    127
32    131
33    135
34    139
35    143
36    147
37    151
38    155
39    159
40    163
41    167
42    171
43    175
44    179
45    183
46    187
47    191
48    195
49    199
dtype: int64
Subtraction Of  Two Series:
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
dtype: int64
Multiplication Of  Tw

Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [ ]:
import pandas as pd
l1=([i for i in range(1,1000) if i%7==0])
l2=([i for i in range(1,1000) if i%11==0])
d1 = pd.Series(l1)
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87  

Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [ ]:
import numpy as np
import pandas as pd
l1=([i for i in range(1,1001) if i%10==0])
a = np.array(l1)
print(f"NumPy array:\n{a}")
print(f"Converted Pandas series:\n{pd.Series(a)}")

NumPy array:
[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]
Converted Pandas series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(f"Original Data Series:\n{s1}")
print(f"Series to an array:\n{np.array(s1.values.tolist())}")

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array:
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(f"Original Data Series:\n{s}")
print(pd.Series(s).sort_values())

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [ ]:
import pandas as pd
s = pd.Series(([i for i in range(1,1001) if i%10==0]))
print(f"Original Data Series:\n{s}")
print(f"Subset of the above Data Series:\n{s[s%7==0]}\n{s[s%5==0]}")


Original Data Series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64
Subset of the above Data Series:
6      70
13    140
20    210
27    280
34    350
41    420
48    490
55    560
62    630
69    700
76    770
83    840
90    910
97    980
dtype: int64
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
l=[2]
for v in range(3,1001):
  for n in range(2, v): 
    if (v % n) == 0: 
      break
    elif(n==v-1):
      l.append(v)
s = pd.Series(l)
print(f"Original Data Series:\n{s}")
print(f"Mean of the said Data Series:\n{s.mean()}")
print(f"Standard deviation of the said Data Series:\n{s.std()}")
print(f"Max of the said Data Series:\n{s.max()}")
print(f"Min of the said Data Series:\n{s.min()}")

Original Data Series:
0        2
1        3
2        5
3        7
4       11
      ... 
163    971
164    977
165    983
166    991
167    997
Length: 168, dtype: int64
Mean of the said Data Series:
453.13690476190476
Standard deviation of the said Data Series:
298.19241719366255
Max of the said Data Series:
997
Min of the said Data Series:
2


Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
l1=([i for i in range(0,1001) if i%7!=0 and i%2!=0])
l2=([i for i in range(0,1001) if i%2==0 and i%5!=0])
l3=([i for i in range(0,1001) if i%2!=0 and i%3!=0])
df = pd.DataFrame({'X':([i for i in range(0,1001) if i%7!=0 and i%2!=0])});
df = pd.DataFrame({'Y':([i for i in range(0,1001) if i%2==0 and i%5!=0])});
df = pd.DataFrame({'Z':([i for i in range(0,1001) if i%2!=0 and i%3!=0])});
df

Z
0      1
1      5
2      7
3     11
4     13
..   ...
328  985
329  989
330  991
331  995
332  997

[333 rows x 1 columns]

Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [13]:
import pandas as pd
df = pd.read_csv('movie.csv.txt')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

First 10 rows of the DataFrame:
       a
0      s
1      d
2      s
3      d
4      s
5      b
6  ramya
7   maha
8    cse


Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

In [17]:
import pandas as pd
df = pd.read_csv('movie.csv.txt')
seventh_movie = df.iloc[6]
print("Details of the seventh moviee:")
print(seventh_movie)

Details of the seventh moviee:
a    ramya
Name: 6, dtype: object


Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three field

In [18]:
import pandas as pd 
data=pd.read_csv("movies.csv") 
data.sort_values(["Year", "Name"], axis=0, 
                 ascending=True, inplace=True)  
data

Name  Year  Unnamed: 2   Language
7      rajkimar  2001         NaN    kannada
6           kgf  2005         NaN    kannada
5        googly  2006         NaN    kannada
4   incredibles  2007         NaN    english
2         barfi  2008         NaN     hindhi
3         fidaa  2009         NaN     telugu
0      bahubali  2010         NaN     telugu
9         jeeva  2012         NaN  malayalam
8          abhi  2020         NaN   gujarthi
1  finding nemo  2020         NaN    english

Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [27]:
import pandas as pd 
data=pd.read_csv("movies.csv") 
data.sort_values(["country", "Language"], axis=0, 
                 ascending=True, inplace=True)  
data

Name  Year     country  Language
4     malla  2007     algeris      tulu
1      raja  2020      angola   english
3     kalla  2009   australia    telugu
2      rani  2008  bangladesh    hindhi
5    googly  2006        cuba    marati
6       kgf  2005      cyprus   bengali
8      abhi  2020    dominica  gujarthi
7  rajkimar  2001       egypt   kannada
9     jeeva  2012      france      onum
0      gaja  2010       india   kannada


Write a NumPy program to generate 8 random integers between 100 and 300



In [28]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[253 181 178 273 216 200 247 252]


Write a NumPy program to create a random integer nos of size 20 and sort it.

In [29]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.52444704 0.70832891 0.58103302 0.0475159  0.16136644 0.43242822
 0.43404289 0.00477362 0.36058125 0.30079629 0.31733971 0.27675342
 0.343205   0.3667113  0.50239289 0.50434655 0.6202044  0.12439028
 0.42743299 0.83968381]
Sorted array:
[0.00477362 0.0475159  0.12439028 0.16136644 0.27675342 0.30079629
 0.31733971 0.343205   0.36058125 0.3667113  0.42743299 0.43242822
 0.43404289 0.50239289 0.50434655 0.52444704 0.58103302 0.6202044
 0.70832891 0.83968381]


Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [30]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.99164712 0.65920602 0.25544066 0.02945342 0.19142209 0.07379265
  0.02123736 0.64045368 0.2193505  0.66752246]
 [0.6526458  0.61417415 0.70188259 0.43765601 0.90520729 0.60654967
  0.99069938 0.71605484 0.66629534 0.70002238]
 [0.81908574 0.54498791 0.75860909 0.45620576 0.41432684 0.47241951
  0.09391875 0.03578339 0.67674162 0.97578936]
 [0.00902741 0.87882841 0.64426297 0.02305119 0.6750231  0.27778708
  0.93840155 0.17596261 0.03072827 0.38113847]
 [0.25973701 0.9695734  0.46320151 0.75730851 0.73201894 0.8047369
  0.3028886  0.49770974 0.79254657 0.23252858]
 [0.62274457 0.14587239 0.03178828 0.62839417 0.48264851 0.67283624
  0.49850339 0.29797087 0.07318519 0.70950383]
 [0.00453829 0.76842627 0.63294887 0.78294993 0.22461388 0.18912814
  0.33763503 0.72652768 0.71097012 0.72261084]
 [0.24390901 0.2804798  0.7207551  0.84401901 0.7626824  0.81448995
  0.6138131  0.33986413 0.54396286 0.5610449 ]
 [0.61038255 0.93238668 0.30553455 0.83901613 0.19234623 0.350319

Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable.

In [31]:
import numpy as np
x = np.random.rand(4, 4)
print("Original array: ")
print(x)
y= x[:2, :3]
print("Second and third rows of the above array:")
print(y)

Original array: 
[[0.02436069 0.80619295 0.18536866 0.59112536]
 [0.56539564 0.82360138 0.24053498 0.02728507]
 [0.21963413 0.57178582 0.72508182 0.31642096]
 [0.3643751  0.99989464 0.48120674 0.77860013]]
Second and third rows of the above array:
[[0.02436069 0.80619295 0.18536866]
 [0.56539564 0.82360138 0.24053498]]


Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame #(movie_metadata.csv file).

In [34]:
import pandas as pd
import numpy as np
df = pd.read_csv('moviees.csv')
small_df = df[['rating','budget','year']]
for i in range(1,len(df)+1):
  if i%5==0:
    print(f"{small_df.iloc[i]}\n")

rating       3
budget    80cr
year      2019
Name: 5, dtype: object

rating        5
budget    50cr 
year       2010
Name: 10, dtype: object

